# Generated by Django 4.2.3 on 2023-08-09 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='is_read',
            new_name='is_done',
        ),
        migrations.RemoveField(
            model_name='daily',
            name='user',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='user',
        ),
    ]
